

export let Config = {
    "category" : "", //32982;gta;27471;minecraft
    "titleToCheck" : "",
    "clientId" : "magcfm9155x67mc5tcfud1larpcmnd",
    "clientSecret" : "49txcolcipub83gvk6a4pyqxls02rp",
    "users" : [
        "miraipanda_",
        "hookibibi",
        "kc_ohio",
        "5dcaster",
        "uki__yo",
        "Naelyetv",
        "shilderi",
        "Encoretoisnake",
        "Aurryuken",
        "adele_th",
        "YaBoiMonik",
        "Usm_deadop",
        "kosuke",
        "Myinana",
        "schoolofbou",
        "Yuumeih",
        "pi0rbal_",
        "Crizis_Hargo",
        "ArtemisWl_",
        "lowhy_lol",
        "FreedomsHostage",
        "kyussey",
        "diane____",
        "starrk__tv",
        "TwinJetNebula",
        "MaxLaite",
        "scailzzz",
        "Konzendooji",
        "LaZerLZ",
        "LilouMuloup",
        "ZykRuk",
        "leyasupls",
        "feurret",
        "RevealUrLove",
        "runike_",
        "sigismundd",
        "Opex0707",
        "exarayn",
        "frannouche_",
        "Celest0z",
        "Fehrteen_one",
        "nishi774",
        "sylphalia_",
        "xalomon_",
        "NakaStream",
        "Atreiidys",
        "salamanderesport",
        "Exeloh",
        "lolskiddo_",
        "Mitsuan",
        "Voxioo",
        "PetrichorLIVE",
        "tpk_live",
        "apsaphea"
    ]

}


